/* NO EYES — dados dos 16 enigmas (conteúdo original, sem alterações) */
window.NOEYES_ENIGMAS = [
  {
    id: 1,
    code: "NE-01",
    title: "Onde a visão termina",
    classification: "INTERNO",
    kind: "text",
    lines: [
      "O arquivo começa onde a visão termina.",
      "O que o olho não pode ver, a mente ainda guarda.",
      "Resposta: a palavra de 5 letras que significa “sem visão”.",
    ],
    answers: ["CEGUE", "CEGOS", "CEGAS"],
  },
  {
    id: 2,
    code: "NE-02",
    title: "Corredor sem janelas",
    classification: "INTERNO",
    kind: "doors",
    lines: [
      "Em um corredor sem janelas, três portas.",
      "Só uma fala a verdade. Qual porta você abre?",
    ],
    answers: ["PORTA2", "2", "SEGUNDA", "ASEGUNDA", "PORTADOIS"],
  },
  {
    id: 3,
    code: "NE-03",
    title: "Mensagem interceptada",
    classification: "CIFRADO",
    kind: "cipher",
    lines: [
      "Mensagem interceptada:",
      "YVCCIRVI",
      "Cifra de César com deslocamento igual ao número de olhos que um humano normalmente tem.",
    ],
    answers: ["ARQUIVO"],
  },
  {
    id: 4,
    code: "NE-04",
    title: "Sala das câmeras",
    classification: "EVIDÊNCIA",
    kind: "text",
    lines: [
      "Em uma sala escura há 7 câmeras.",
      "4 estão ligadas.",
      "2 gravam apenas áudio.",
      "1 está desligada e olhando para o teto.",
      "Quantas câmeras realmente “veem”?",
    ],
    answers: ["4", "QUATRO"],
  },
  {
    id: 5,
    code: "NE-05",
    title: "Rearranjo",
    classification: "PROTOCOLO",
    kind: "text",
    lines: [
      "Rearranje as letras:",
      "“NO EYES” + “ARQUIVO”",
      "para formar a frase que o sistema usa quando alguém tenta entrar sem autorização.",
    ],
    answers: ["ACESSONEGADO", "ACESSO NEGADO"],
  },
  {
    id: 6,
    code: "NE-06",
    title: "Sinal em pulsos",
    classification: "INTERCEPTADO",
    kind: "morse",
    lines: ["-.-. .- ... ---   -.-. . -. ... ---"],
    answers: ["CASOCENSO", "CASO CENSO"],
  },
  {
    id: 7,
    code: "NE-07",
    title: "Quem observa",
    classification: "INTERNO",
    kind: "observe",
    lines: [
      "Se:",
      "A vê B",
      "B não vê C",
      "C vê A",
      "e ninguém vê a si mesmo...",
      "Quem está sendo observado por mais pessoas?",
    ],
    answers: ["A"],
  },
  {
    id: 8,
    code: "NE-08",
    title: "Número de série",
    classification: "FICHA",
    kind: "text",
    lines: [
      "O número de série do arquivo perdido é:",
      "1  4  9  16  25  36  ?",
      "Qual é o próximo número da sequência?",
    ],
    answers: ["49"],
  },
  {
    id: 9,
    code: "NE-09",
    title: "Espelho",
    classification: "NÃO ARQUIVADO",
    kind: "text",
    lines: [
      "Você olha para um espelho e não vê seu rosto.",
      "Em vez disso, vê a palavra “SEM”.",
      "O que o espelho está tentando te dizer sobre o arquivo?",
    ],
    answers: ["SEMOLHOS", "SEM OLHOS", "NOEYES", "NO EYES"],
  },
  {
    id: 10,
    code: "NE-10",
    title: "Sinais de intrusão",
    classification: "ALERTA",
    kind: "signals",
    lines: [
      "Quando o sistema detecta intrusão, ele envia três sinais:",
      "VERMELHO — AMARELO — VERMELHO",
      "O que o operador deve responder para confirmar “acesso autorizado”?",
      "(Use a sequência lógica de cores de alerta invertida.)",
    ],
    answers: ["VERDE"],
  },
  {
    id: 11,
    code: "NE-11",
    title: "Binário",
    classification: "CIFRADO",
    kind: "binary",
    lines: ["01001110 01001111", "Converta e diga o que aparece."],
    answers: ["NO"],
  },
  {
    id: 12,
    code: "NE-12",
    title: "Vogais apagadas",
    classification: "APAGADO",
    kind: "text",
    lines: [
      "A frase original era:",
      "“OS OLHOS ESTÃO SEMPRE ABERTOS”",
      "Alguém apagou todas as vogais.",
      "Reconstrua a frase e pegue apenas as consoantes da terceira palavra.",
    ],
    answers: ["STM"],
  },
  {
    id: 13,
    code: "NE-13",
    title: "Contagem",
    classification: "INTERNO",
    kind: "text",
    lines: [
      "Quantas vezes a letra “E” aparece na frase completa:",
      "“NO EYES ARQUIVO INTERNO CLASSIFICADO NIVEL ZERO”",
    ],
    answers: ["7", "SETE", "5", "CINCO"],
  },
  {
    id: 14,
    code: "NE-14",
    title: "Cinco portas",
    classification: "PROTOCOLO",
    kind: "text",
    lines: [
      "Você está em uma sala com 5 portas numeradas.",
      "A porta correta é a única cujo número:",
      "— é ímpar",
      "— é maior que 2",
      "— e quando elevado ao quadrado dá um número terminado em 9",
    ],
    answers: ["3", "TRES", "TRÊS", "PORTA3"],
  },
  {
    id: 15,
    code: "NE-15",
    title: "Mensagem final",
    classification: "RESTRITO",
    kind: "text",
    lines: [
      "A mensagem final do arquivo diz:",
      "“O que você não pode ver ainda te observa.”",
      "Qual é a palavra de 7 letras que resume essa ideia?",
    ],
    answers: ["PARADOXO"],
  },
  {
    id: 16,
    code: "NE-16",
    title: "Frase de liberação",
    classification: "NÍVEL ZERO",
    kind: "keys",
    lines: [
      "Junte as 15 chaves parciais na ordem e extraia apenas as letras maiúsculas que formam a frase final de liberação.",
      "A frase completa deve ser digitada em maiúsculas, sem espaços.",
    ],
    answers: [
      "CEGUEPORTA2ARQUIVO4ACESSONEGADOCASOCENSOA49SEMOLHOSVERDENOSTM73PARADOX",
      "CEGUEPORTA2ARQUIVO4ACESSONEGADOCASOCENSOA49SEMOLHOSVERDENOSTM73PARADOXO",
    ],
  },
];

window.NOEYES_TOTAL = window.NOEYES_ENIGMAS.length;

window.NOEYES_ARCHIVE = "https://flsaki.github.io/no-eyes/";
